(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good Afternoon Frederic, Welcome to Coot version 0.8.9.1")
(use-graphics-interface-state)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good afternoon Frederic. Welcome to Coot 0.8.9.1")
(set-display-lists-for-maps 0)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(make-and-draw-map-with-reso-with-refmac-params "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/refmac-cmdline-test/out.mtz" "FWT" "PHWT" "" 0 0 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0  0.00  0.00)
(make-and-draw-map-with-reso-with-refmac-params "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/refmac-cmdline-test/out.mtz" "DELFWT" "PHDELWT" "" 0 1 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0  0.00  0.00)
(coot-checked-exit 0)
(clear-backups-maybe)
(stereo-mode-state)
(stereo-mode-state)
(save-state)
