filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good Evening Frederic, Welcome to Coot version 0.8.9.1")
use_graphics_interface_state ()
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good evening Frederic. Welcome to Coot 0.8.9.1")
set_display_lists_for_maps (0)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
make_and_draw_map_with_reso_with_refmac_params ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/refmac-cmdline-test/out.mtz", "FWT", "PHWT", "", 0, 0, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0,  0.00,  0.00)
make_and_draw_map_with_reso_with_refmac_params ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/refmac-cmdline-test/out.mtz", "DELFWT", "PHDELWT", "", 0, 1, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0,  0.00,  0.00)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/refmac-cmdline-test/out.pdb", 1)
graphics_molecule_bond_type (2)
get_show_symmetry ()
get_show_unit_cell (0)
set_show_symmetry_master (1)
set_show_unit_cells_all (0)
set_symmetry_atom_labels_expanded (0)
set_show_symmetry_master (1)
set_show_unit_cells_all (0)
set_symmetry_atom_labels_expanded (0)
set_contour_level_absolute ( 0.33)
set_contour_level_absolute ( 0.00)
set_contour_level_absolute ( 0.10)
set_contour_level_absolute ( 0.10)
set_contour_level_absolute ( 0.20)
set_contour_level_in_sigma ( 1.00)
set_contour_level_in_sigma ( 0.50)
set_contour_level_in_sigma ( 0.50)
set_contour_level_in_sigma ( 1.00)
set_contour_level_in_sigma ( 0.20)
;; # DIRECT SCHEME ((graphics-general-key-press-hook 97))
coot_checked_exit (0)
;; # DIRECT SCHEME ((clear-backups-maybe))
stereo_mode_state ()
stereo_mode_state ()
save_state ()
