# These commands are the saved state of coot.  You can evaluate them
# using "Calculate->Run Script...".
#;;molecule-info: out.mtz FWT PHWT
#;;molecule-info: out.mtz DELFWT PHDELWT
#;;molecule-info: out.pdb
set_graphics_window_size (1102, 830)
set_graphics_window_position (0, 1)
set_display_control_dialog_position (849, 0)
vt_surface (2)
set_clipping_front ( 0.00)
set_clipping_back ( 0.00)
set_map_radius (25.00)
set_iso_level_increment ( 0.0500)
set_diff_map_iso_level_increment ( 0.0050)
set_colour_map_rotation_on_read_pdb (21.00)
set_colour_map_rotation_on_read_pdb_flag (1)
set_colour_map_rotation_on_read_pdb_c_only_flag (1)
set_swap_difference_map_colours (0)
set_background_colour ( 0.00,  0.00,  0.00)
set_symmetry_size (13.00)
set_symmetry_colour_merge ( 0.50)
set_symmetry_colour ( 0.10,  0.20,  0.80)
set_symmetry_atom_labels_expanded (0)
set_active_map_drag_flag (1)
set_show_aniso (0)
set_aniso_probability (50.00)
set_smooth_scroll_steps (40)
set_smooth_scroll_limit (10.00)
set_font_size (2)
set_rotation_centre_size ( 0.10)
set_do_anti_aliasing (0)
set_default_bond_thickness (5)
set_map_sampling_rate ( 1.80)
make_and_draw_map ("out.mtz", "FWT", "PHWT", "", 0, 0)
set_last_map_colour ( 0.20,  0.50,  0.70)
set_last_map_contour_level (6.887660e-02)
set_last_map_sigma_step ( 0.10)
make_and_draw_map ("out.mtz", "DELFWT", "PHDELWT", "", 0, 1)
set_last_map_colour ( 0.20,  0.60,  0.20)
set_last_map_contour_level (3.700000e-01)
set_last_map_sigma_step ( 0.10)
set_map_displayed (1, 0)
handle_read_draw_molecule ("out.pdb")
set_molecule_bonds_colour_map_rotation (2, 63.00)
set_draw_hydrogens (2, 1)
set_scroll_wheel_map (0)
set_matrix (60.00)
set_show_symmetry_master (1)
set_go_to_atom_molecule (2)
scale_zoom ( 0.34)
set_rotation_centre (-0.09,  8.58,  7.39)
set_view_quaternion (-0.1323,  0.2888,  0.5469,  0.7746)
post_display_control_window ()
