; These commands are the saved state of coot.  You can evaluate them
; using "Calculate->Run Script...".
;;molecule-info: out.mtz FWT PHWT
;;molecule-info: out.mtz DELFWT PHDELWT
;;molecule-info: out.pdb
(set-graphics-window-size 1102 830)
(set-graphics-window-position 0 1)
(set-display-control-dialog-position 849 0)
(vt-surface 2)
(set-clipping-front  0.00)
(set-clipping-back  0.00)
(set-map-radius 25.00)
(set-iso-level-increment  0.0500)
(set-diff-map-iso-level-increment  0.0050)
(set-colour-map-rotation-on-read-pdb 21.00)
(set-colour-map-rotation-on-read-pdb-flag 1)
(set-colour-map-rotation-on-read-pdb-c-only-flag 1)
(set-swap-difference-map-colours 0)
(set-background-colour  0.00  0.00  0.00)
(set-symmetry-size 13.00)
(set-symmetry-colour-merge  0.50)
(set-symmetry-colour  0.10  0.20  0.80)
(set-symmetry-atom-labels-expanded 0)
(set-active-map-drag-flag 1)
(set-show-aniso 0)
(set-aniso-probability 50.00)
(set-smooth-scroll-steps 40)
(set-smooth-scroll-limit 10.00)
(set-font-size 2)
(set-rotation-centre-size  0.10)
(set-do-anti-aliasing 0)
(set-default-bond-thickness 5)
(set-map-sampling-rate  1.80)
(make-and-draw-map "out.mtz" "FWT" "PHWT" "" 0 0)
(set-last-map-colour  0.20  0.50  0.70)
(set-last-map-contour-level 6.887660e-02)
(set-last-map-sigma-step  0.10)
(make-and-draw-map "out.mtz" "DELFWT" "PHDELWT" "" 0 1)
(set-last-map-colour  0.20  0.60  0.20)
(set-last-map-contour-level 3.700000e-01)
(set-last-map-sigma-step  0.10)
(set-map-displayed 1 0)
(handle-read-draw-molecule "out.pdb")
(set-molecule-bonds-colour-map-rotation 2 63.00)
(set-draw-hydrogens 2 1)
(set-scroll-wheel-map 0)
(set-matrix 60.00)
(set-show-symmetry-master 1)
(set-go-to-atom-molecule 2)
(scale-zoom  0.34)
(set-rotation-centre -0.09  8.58  7.39)
(set-view-quaternion -0.1323  0.2888  0.5469  0.7746)
(post-display-control-window)
