(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good Evening Frederic, Welcome to Coot version 0.8.9.1")
(use-graphics-interface-state)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good evening Frederic. Welcome to Coot 0.8.9.1")
(set-display-lists-for-maps 0)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(make-and-draw-map-with-reso-with-refmac-params "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/refmac-cmdline-test/out.mtz" "FWT" "PHWT" "" 0 0 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0  0.00  0.00)
(make-and-draw-map-with-reso-with-refmac-params "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/refmac-cmdline-test/out.mtz" "DELFWT" "PHDELWT" "" 0 1 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0  0.00  0.00)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/refmac-cmdline-test/out.pdb" 1)
(graphics-molecule-bond-type 2)
(get-show-symmetry)
(get-show-unit-cell 0)
(set-show-symmetry-master 1)
(set-show-unit-cells-all 0)
(set-symmetry-atom-labels-expanded 0)
(set-show-symmetry-master 1)
(set-show-unit-cells-all 0)
(set-symmetry-atom-labels-expanded 0)
(set-contour-level-absolute  0.33)
(set-contour-level-absolute  0.00)
(set-contour-level-absolute  0.10)
(set-contour-level-absolute  0.10)
(set-contour-level-absolute  0.20)
(set-contour-level-in-sigma  1.00)
(set-contour-level-in-sigma  0.50)
(set-contour-level-in-sigma  0.50)
(set-contour-level-in-sigma  1.00)
(set-contour-level-in-sigma  0.20)
(graphics-general-key-press-hook 97)
(coot-checked-exit 0)
(clear-backups-maybe)
(stereo-mode-state)
(stereo-mode-state)
(save-state)
