(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good Afternoon Frederic, Welcome to Coot version 0.8.9.1")
(use-graphics-interface-state)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good afternoon Frederic. Welcome to Coot 0.8.9.1")
(set-display-lists-for-maps 0)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(set-find-hydrogen-torsion 1)
(use-graphics-interface-state)
(handle-read-draw-molecule-with-recentre "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_1/.comm/tmp.refine.pdb" 1)
(set-molecule-bonds-colour-map-rotation 0 140.00)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 1)
(close-molecule 2)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 3)
(close-molecule 4)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 5)
(close-molecule 6)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 7)
(close-molecule 8)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 9)
(close-molecule 10)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 11)
(close-molecule 12)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 13)
(close-molecule 14)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 15)
(close-molecule 16)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 0)
(close-molecule 17)
(close-molecule 18)
(handle-read-draw-molecule-with-recentre "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_1/solvent-correction_refine_1.pdb" 1)
(set-molecule-bonds-colour-map-rotation 19 30.00)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_1/solvent-correction_refine_1.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_1/solvent-correction_refine_1.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 20)
(close-molecule 21)
(handle-read-draw-molecule-with-recentre "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_1/.comm/tmp.refine.pdb" 1)
(set-molecule-bonds-colour-map-rotation 22 140.00)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 23)
(close-molecule 24)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 25)
(close-molecule 26)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 22)
(close-molecule 27)
(close-molecule 28)
(close-molecule 19)
(handle-read-draw-molecule-with-recentre "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_1/4y9h_refine_1.pdb" 1)
(set-molecule-bonds-colour-map-rotation 29 30.00)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_1/4y9h_refine_1.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_1/4y9h_refine_1.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 30)
(close-molecule 31)
(handle-read-draw-molecule-with-recentre "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_2/.comm/tmp.refine.pdb" 1)
(set-molecule-bonds-colour-map-rotation 32 140.00)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_2/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_2/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 33)
(close-molecule 34)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_2/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_2/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 35)
(close-molecule 36)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_2/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_2/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 37)
(close-molecule 38)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_2/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_2/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 39)
(close-molecule 40)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_2/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_2/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 41)
(close-molecule 42)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_2/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_2/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 43)
(close-molecule 44)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_2/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_2/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 45)
(close-molecule 46)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_2/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_2/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 47)
(close-molecule 48)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_2/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_2/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 49)
(close-molecule 50)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_2/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_2/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 51)
(close-molecule 52)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_2/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_2/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 53)
(close-molecule 54)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_2/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_2/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 55)
(close-molecule 56)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_2/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_2/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 57)
(close-molecule 58)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_2/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_2/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 59)
(close-molecule 60)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_2/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_2/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 61)
(close-molecule 62)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_2/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_2/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 63)
(close-molecule 64)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_2/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_2/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 32)
(close-molecule 65)
(close-molecule 66)
(close-molecule 29)
(handle-read-draw-molecule-with-recentre "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_2/solvent-correction_refine_2.pdb" 1)
(set-molecule-bonds-colour-map-rotation 67 30.00)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_2/solvent-correction_refine_2.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_2/solvent-correction_refine_2.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 68)
(close-molecule 69)
(handle-read-draw-molecule-with-recentre "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_2/.comm/tmp.refine.pdb" 1)
(set-molecule-bonds-colour-map-rotation 70 140.00)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_2/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_2/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 70)
(close-molecule 71)
(close-molecule 72)
(close-molecule 67)
(handle-read-draw-molecule-with-recentre "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_2/4y9h_refine_2.pdb" 1)
(set-molecule-bonds-colour-map-rotation 73 30.00)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_2/4y9h_refine_2.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_2/4y9h_refine_2.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(coot-checked-exit 0)
(clear-backups-maybe)
(save-state)
