filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good Afternoon Frederic, Welcome to Coot version 0.8.9.1")
use_graphics_interface_state ()
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good afternoon Frederic. Welcome to Coot 0.8.9.1")
set_display_lists_for_maps (0)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
set_find_hydrogen_torsion (1)
use_graphics_interface_state ()
handle_read_draw_molecule_with_recentre ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_1/.comm/tmp.refine.pdb", 1)
set_molecule_bonds_colour_map_rotation (0, 140.00)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (1)
close_molecule (2)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (3)
close_molecule (4)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (5)
close_molecule (6)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (7)
close_molecule (8)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (9)
close_molecule (10)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (11)
close_molecule (12)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (13)
close_molecule (14)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (15)
close_molecule (16)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (0)
close_molecule (17)
close_molecule (18)
handle_read_draw_molecule_with_recentre ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_1/solvent-correction_refine_1.pdb", 1)
set_molecule_bonds_colour_map_rotation (19, 30.00)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_1/solvent-correction_refine_1.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_1/solvent-correction_refine_1.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (20)
close_molecule (21)
handle_read_draw_molecule_with_recentre ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_1/.comm/tmp.refine.pdb", 1)
set_molecule_bonds_colour_map_rotation (22, 140.00)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (23)
close_molecule (24)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (25)
close_molecule (26)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (22)
close_molecule (27)
close_molecule (28)
close_molecule (19)
handle_read_draw_molecule_with_recentre ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_1/4y9h_refine_1.pdb", 1)
set_molecule_bonds_colour_map_rotation (29, 30.00)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_1/4y9h_refine_1.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_1/4y9h_refine_1.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (30)
close_molecule (31)
handle_read_draw_molecule_with_recentre ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_2/.comm/tmp.refine.pdb", 1)
set_molecule_bonds_colour_map_rotation (32, 140.00)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (33)
close_molecule (34)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (35)
close_molecule (36)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (37)
close_molecule (38)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (39)
close_molecule (40)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (41)
close_molecule (42)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (43)
close_molecule (44)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (45)
close_molecule (46)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (47)
close_molecule (48)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (49)
close_molecule (50)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (51)
close_molecule (52)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (53)
close_molecule (54)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (55)
close_molecule (56)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (57)
close_molecule (58)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (59)
close_molecule (60)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (61)
close_molecule (62)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (63)
close_molecule (64)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (32)
close_molecule (65)
close_molecule (66)
close_molecule (29)
handle_read_draw_molecule_with_recentre ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_2/solvent-correction_refine_2.pdb", 1)
set_molecule_bonds_colour_map_rotation (67, 30.00)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_2/solvent-correction_refine_2.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/6f1l/Refine_2/solvent-correction_refine_2.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (68)
close_molecule (69)
handle_read_draw_molecule_with_recentre ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_2/.comm/tmp.refine.pdb", 1)
set_molecule_bonds_colour_map_rotation (70, 140.00)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (70)
close_molecule (71)
close_molecule (72)
close_molecule (67)
handle_read_draw_molecule_with_recentre ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_2/4y9h_refine_2.pdb", 1)
set_molecule_bonds_colour_map_rotation (73, 30.00)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_2/4y9h_refine_2.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/Refine_2/4y9h_refine_2.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
coot_checked_exit (0)
;; # DIRECT SCHEME ((clear-backups-maybe))
save_state ()
