; These commands are the saved state of coot.  You can evaluate them
; using "Calculate->Run Script...".
;;molecule-info: out_solvent.pdb
(set-graphics-window-size 1080 766)
(set-graphics-window-position 0 0)
(set-display-control-dialog-position 20 20)
(vt-surface 2)
(set-clipping-front  0.00)
(set-clipping-back  0.00)
(set-map-radius 12.60)
(set-iso-level-increment  0.0500)
(set-diff-map-iso-level-increment  0.0050)
(set-colour-map-rotation-on-read-pdb 21.00)
(set-colour-map-rotation-on-read-pdb-flag 1)
(set-colour-map-rotation-on-read-pdb-c-only-flag 1)
(set-swap-difference-map-colours 0)
(set-background-colour  0.00  0.00  0.00)
(set-symmetry-size 13.00)
(set-symmetry-colour-merge  0.50)
(set-symmetry-colour  0.10  0.20  0.80)
(set-symmetry-atom-labels-expanded 0)
(set-active-map-drag-flag 1)
(set-show-aniso 0)
(set-aniso-probability 50.00)
(set-smooth-scroll-steps 40)
(set-smooth-scroll-limit 10.00)
(set-font-size 2)
(set-rotation-centre-size  0.10)
(set-do-anti-aliasing 0)
(set-default-bond-thickness 5)
(set-map-sampling-rate  1.80)
(handle-read-draw-molecule "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/refmac-cmdline-test/out_solvent.pdb")
(set-molecule-bonds-colour-map-rotation 0 21.00)
(set-draw-hydrogens 0 1)
(set-matrix 60.00)
(set-show-symmetry-master 0)
(set-go-to-atom-molecule 0)
(scale-zoom  1.00)
(set-rotation-centre 21.58 14.34  3.02)
(set-view-quaternion  0.3403 -0.1784  0.0163  0.9231)
