(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good Evening Frederic, Welcome to Coot version 0.8.9.1")
(use-graphics-interface-state)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good evening Frederic. Welcome to Coot 0.8.9.1")
(set-display-lists-for-maps 0)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/refmac-cmdline-test/out_solvent.pdb" 1)
(graphics-molecule-bond-type 0)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(graphics-molecule-bond-type 0)
(coot-checked-exit 0)
(clear-backups-maybe)
(stereo-mode-state)
(stereo-mode-state)
(save-state)
