filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good Evening Frederic, Welcome to Coot version 0.8.9.1")
use_graphics_interface_state ()
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good evening Frederic. Welcome to Coot 0.8.9.1")
set_display_lists_for_maps (0)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/Users/fpoitevi/gdrive/Toolkit/MPflat/systems/4y9h/refmac-cmdline-test/out_solvent.pdb", 1)
graphics_molecule_bond_type (0)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
graphics_molecule_bond_type (0)
coot_checked_exit (0)
;; # DIRECT SCHEME ((clear-backups-maybe))
stereo_mode_state ()
stereo_mode_state ()
save_state ()
